# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 883407424cab137a631a49a409c11845265aeda7eeda8798fe2d1d99b2a0b92dc738cb3ac85c43fa978cadca57a61733c2d69015b7f2ec343a33ee79967c78cf

test:
  secret_key_base: 125df273fae0d5268aa276ebd515dd8646e3ad482ef1e94477103c77c14caef154addd03f9a14251429b116528eeba2335359d786c9b66e5cccbeab7313463b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
